<?php

/**
 * @file
 * Contains tasker.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function tasker_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the tasker module.
    case 'help.page.tasker':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Tasker - for creating tasks to junior developer and evaluating time of task completion.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function tasker_theme() {
  return [
    'tasker' => [
      'render element' => 'children',
    ],
  ];
}
