<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\cdp_registration\Form\DeveloperRegisterForm;
use Drupal\cdp_registration\Form\TechleadRegisterForm;
/**
 * @file
 * Primary module hooks for Custom registration module and login.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_entity_type_alter().
 */
function cdp_registration_entity_type_alter(array &$entity_types)
{
  $entity_types['user']->setFormClass('registration_developers', \Drupal\cdp_registration\Form\CustomRegisterForm::class);
  $entity_types['user']->setFormClass('registration_techlead', \Drupal\cdp_registration\Form\CustomRegisterForm::class);
}


/**
 * Implements hook_form_FORM_ID_alter().
 */
function cdp_registration_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
  $form['name']['#access'] = FALSE;
  $form['mail'] = [
    '#type' => 'email',
    '#title' => t('E-mail'),
    '#description' => t('Enter your email.'),
    '#required' => TRUE,
    '#weight' => -1,
  ];
  $form['#validate'] = array_merge(['cdp_registration_form_alter_validate_mail'], $form['#validate']);
}


/**
 * Implements hook_form_FORM_ID_alter().
 */
function cdp_registration_form_alter_validate_mail(array &$form, FormStateInterface $form_state): void
{
  $mail = $form_state->getValue('mail');
  $user = user_load_by_mail($mail);
  if ($user) {
    $form_state->setValue('name', $user->getAccountName());
  }
}
